version: "3"
services:


  postgresql:
    container_name: file_postgres
    image: postgres:13
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data_7:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: file_postgresdb
      TZ: Asia/Tashkent
    networks:
        - file_network



  rabbitmq:
    container_name: file_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: Asia/Tashkent
    networks:
      - file_network

  minio:
    container_name: file_minio
    image: minio/minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"

    networks:
      - file_network


  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    hostname: redis
    command: redis-server
    networks:
      - file_network



  mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  rabbitmq_data:
  minio_data:
  influxdb_data:
  influxconfig:
  postgresql_data_6:
  postgresql_data_7:
  cache:


networks:
  file_network: